apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: parrotdev-svc
  namespace: prueba
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: parrotdev
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrotdev
  namespace: prueba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrotdev
  template:
    metadata:
      labels:
        app: parrotdev
    spec:
      containers:
      - command:
        - python
        - manage.py
        - runserver
        - 0.0.0.0:8000
        env:
        - name: POSTGRES_DB
          value: parrot_db
        - name: POSTGRES_USER
          value: parrotparrot
        - name: POSTGRES_PASSWORD
          value: parrotparrot
        - name: POSTGRES_HOST
          value: dbpruebaparrot.ch3ii5tbeuol.us-east-1.rds.amazonaws.com
        - name: POSTGRES_PORT
          value: "5432"
        - name: APP_VERSION
          value: 0.1.0
        image: 087445709447.dkr.ecr.us-east-1.amazonaws.com/parrotdev:12
        imagePullPolicy: IfNotPresent
        name: parrotdev
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
